backend:
  replicaCount: 1
  env:
    datasourceUsername: staging_user

frontend:
  replicaCount: 1

postgres:
  managed:
    dbName: staging

ingress:
  className: nginx
  host: staging.139.59.204.235.sslip.io
  backendRewriteTarget: /users/$2
