backend:
  replicaCount: 1
  env:
    datasourceUsername: staging_user

frontend:
  replicaCount: 1

postgres:
  managed:
    dbName: staging

ingress:
  className: nginx
  host: staging.user-mgmt.local
  backendRewriteTarget: /users/$2
