backend:
  replicaCount: 1
  env:
    datasourceUsername: production_user

frontend:
  replicaCount: 1

postgres:
  managed:
    dbName: production

ingress:
  host: production.139.59.204.235.sslip.io
