backend:
  replicaCount: 1
  env:
    datasourceUsername: production_user

frontend:
  replicaCount: 1

postgres:
  managed:
    dbName: production

ingress:
  host: production.209.38.188.174.sslip.io
