apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    {{- include "user-mgmt-service.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.postgres.managed.host }}:{{ .Values.postgres.managed.port }}/{{ .Values.postgres.managed.dbName }}?sslmode=require"
  SPRING_DATASOURCE_USERNAME: {{ .Values.backend.env.datasourceUsername | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.backend.env.ddlAuto | quote }}
  JWT_ISSUER: {{ .Values.backend.env.jwtIssuer | quote }}
  JWT_EXPIRATION_MILLIS: {{ .Values.backend.env.jwtExpirationMillis | quote }}
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: {{ .Values.postgres.managed.maxPoolSize | quote }}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "DEBUG"
