apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "user-mgmt-service.labels" . | nindent 4 }}
 
spec:
  replicas: {{ .Values.frontend.replicaCount }}
 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
 
  selector:
    matchLabels:
      app: frontend
 
  template:
    metadata:
      labels:
        app: frontend
 
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
 
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
 
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
 
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
 
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
