apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: module-service-servicemonitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: module-service
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
