apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: staging
spec:
  restartPolicy: Never
  containers:
    - name: load-generator
      image: busybox
      command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://backend-service:8080/users/register --post-data='{}' --header='Content-Type: application/json'; done"
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
