grafana:
  enabled: true

  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 1Gi

prometheus:
  enabled: true

  prometheusSpec:
    retention: 7d

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

  config:
    global:
      resolve_timeout: 5m

    route:
      group_by:
        - namespace
        - alertname
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1h
      receiver: webhook

      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: "null"

    receivers:
      - name: "null"

      - name: webhook
        webhook_configs:
          - url: "https://webhook.site/dca8f6a0-b424-45cf-bdc1-6a961c6b9af6"
            send_resolved: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
