apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-specific-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - staging
                - production
      validate:
        message: "Container-Images dürfen nicht den Tag 'latest' verwenden."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
